# Generated by Django 2.0.2 on 2018-02-06 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('many_to_many', '0007_auto_20180206_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facebookuser',
            options={'verbose_name_plural': 'self - FacebookUser'},
        ),
        migrations.AlterModelOptions(
            name='instagramuser',
            options={'verbose_name_plural': 'symmetrical - InstagramUser'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name_plural': 'Basic - Pizza'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Intermediate - Post'},
        ),
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name_plural': 'Intermediate - PostLike'},
        ),
        migrations.AlterModelOptions(
            name='relation',
            options={'verbose_name_plural': 'symmetrical_Intermediate - Relation'},
        ),
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'Basic - Topping'},
        ),
        migrations.AlterModelOptions(
            name='twitteruser',
            options={'verbose_name_plural': 'symmetrical_Intermediate - TwitterUser'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Intermediate - User'},
        ),
    ]
